In [ ]:
# in Anaconda prompt, to avoid SSL certificate try below

# conda config --set ssl_verify no
# conda install -c conda-forge tensorflow


# !pip install --upgrade tensorflow

### intro to Tensors

### getting info from tensors

### manipulating tensors

### tensors and Numpy

### using @tf.function 

# intro to Tensors

In [97]:
import tensorflow as tf
#import tensorflow_probability as tfp
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

ModuleNotFoundError: No module named 'tensorflow_probability'

In [2]:

print(tf.__version__)

2.3.0


## creating tensors with tf.constant()




In [3]:
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar = tf.constant(10)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [5]:
scalar.ndim

0

In [6]:
# create a vector

vector = tf.constant([10,10])
print(vector)

print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [7]:
# create a matrix (has more than 1 dim)

matrix = tf.constant([[10,7],
                      [8,6]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  6]])>

In [8]:
matrix.ndim

2

In [9]:
# create another matrix

another_matrix = tf.constant([[10.,7.],
                             [8.,5.],
                             [5.,9.]], dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 8.,  5.],
       [ 5.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
# lets create a tensor


tensor = tf.constant([[[1,2,3],
                     [4,5,6],
                     [7,8,9],
                      [10,11,12]]])

tensor

<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])>

In [12]:
tensor.ndim

3

In [13]:
tensor1 = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                       [[13,14,15],
                       [16,17,18]]])

tensor1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [14]:
tensor1.ndim


3

## tf.variable

In [15]:
# create the same tensor with tf.variable 


changeable_tensor= tf.Variable([8,5])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 5])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [17]:
# lets try to chang one of the elements

changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [18]:
# lets try .assign()

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 5])>

In [19]:
unchangeable_tensor[0] = 2
unchangeable_tensor

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [20]:
unchangeable_tensor[0].assign(2)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## random tensors



#### Random tensors are tensors of some abitary size which contain random numbers


In [21]:
# create 2 random tensors

random_1 = tf.random.Generator.from_seed(42)    # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))


random_2 = tf.random.Generator.from_seed(42)     # set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))

# are they equal ?
random_1, random_2,  random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [22]:
# create 2 random tensors

random_1 = tf.random.Generator.from_seed(10)    # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))


random_2 = tf.random.Generator.from_seed(10)     # set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))

# are they equal ?
random_1, random_2,  random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [23]:
# shuffle the order of elements in a tensor


# shuffle a tensor

not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [8,3]])

not_shuffled.ndim


# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  3],
       [ 3,  4],
       [10,  7]])>

In [24]:
# shuffle our non_shuffled tensor
tf.random.set_seed(42)                                  # global level random seed
tf.random.shuffle(not_shuffled, seed=42)                # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 8,  3]])>

In [25]:
# Other ways to make tensors


# create tensors with all ones
tf.ones([10,8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
# create tensors with all zeros
tf.zeros([5,8])

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

##  turn numpy arrays into tensors

#### you can also turn numpy arrays into tensors

In [27]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)  # create a numpy array between 1 and 25
numpy_A


# X = tf.constant(some_matrix)    #capital for matrix or tensor
# Y = tf.constant(vector)         # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [28]:
A = tf.constant(numpy_A, shape=(2,3,4))       # turn numpy arrays into tensors     # 2*3*4=24

B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [29]:
A = tf.constant(numpy_A, shape=(8,3))    # 8*3 = 24

A

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])>

In [30]:
A.ndim

2

## getting information from tensors




##### shape    -- tensor.shape
#####  Rank   -- tensor.ndim
#####  size     -- tensor.size(tensor)
#####   axis or dimension  -- tensor[0]

In [31]:
# create a rank 4 tensor (4 dimensions)


rank_4_tensor = tf.zeros(shape=[2,3,4,5])      # 2*3*4*5 = 120

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [33]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)        # 2*3*4*5 = 120

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [34]:
# get various attributes of our tensor

print('datatype of every element: ', rank_4_tensor.dtype)
print('number of dimensions (rank): ', rank_4_tensor.ndim)
print('shape of tensor :', rank_4_tensor.shape)
print('elements along the 0 axis :', rank_4_tensor.shape[0])
print('elements along the last axis :', rank_4_tensor.shape[-1])
print('total no of elements in our tensor: ', tf.size(rank_4_tensor))
print('total no of elements in our tensor: ', tf.size(rank_4_tensor).numpy())

datatype of every element:  <dtype: 'float32'>
number of dimensions (rank):  4
shape of tensor : (2, 3, 4, 5)
elements along the 0 axis : 2
elements along the last axis : 5
total no of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
total no of elements in our tensor:  120


## indexing tensors


#### tensors can be indexed just like python lists

In [35]:
# get the first 2 elements of each dimensions

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:

rank_4_tensor[:2,:2,:3,:4]

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
# get the first element frpom each dimension from each except for the final one

rank_4_tensor[:1,:1,:1,:1]


<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [38]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [39]:
rank_4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [40]:
rank_4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [41]:
# create  a rank 2 tensor (2 dimension)

rank_2_tensor = tf.constant([[10,7],
                            [8,6]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [42]:
rank_2_tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  6]])>

In [43]:
rank_2_tensor[:, -2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8])>

In [44]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]            # adding new dimension on existing one

rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 8],
        [ 6]]])>

In [45]:
# alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis = -1)    # -1  means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 8],
        [ 6]]])>

In [46]:
tf.expand_dims(rank_2_tensor, axis = 0)    #  expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 8,  6]]])>

In [47]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  6]])>

## Manipulating tensors (tensor operations)



#### basic operations like   + , - , * , /

In [48]:
# you can add values to a tensor using the additon operator

tensor = tf.constant([[10,7],
                      [ 8,6]])

tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [18, 16]])>

In [49]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  6]])>

In [50]:
# multiplication  operator


tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [40, 30]])>

In [51]:
# subtract  operator

tensor- 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 2],
       [3, 1]])>

In [52]:
# we can use the tf built-in fun

tf.multiply (tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 80,  60]])>

In [53]:
tf.add (tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [18, 16]])>

In [54]:
tf.subtract (tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-2, -4]])>

## Matrix Multiplication 




#### Rules  -----  the inner dimensions should match   and 
#### Rules  -----  the resulting matrix has the shape of the inner dimensions

In [55]:
# matrix multiplication in tensorflow

print(tensor)

tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 8  6]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[156, 112],
       [128,  92]])>

In [56]:
# matrix multiplication with python operator '@'

print(tensor * tensor)

print( tensor @ tensor)    #    '@ ' plays as a matrix multiplication

tf.Tensor(
[[100  49]
 [ 64  36]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[156 112]
 [128  92]], shape=(2, 2), dtype=int32)


In [57]:
tensor.shape

TensorShape([2, 2])

In [58]:
# create a tensor (3,2) tensor

X = tf.constant ([[1,2],
                 [3,4],
                 [5,6]])


Y = tf.constant ([[7,8],
                 [9,10],
                 [11,12]])


X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [59]:
# try to matrix multiply with same shape

X @ Y

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [60]:
tf.matmul(X,Y)

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [61]:
# lets change the shape of Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [62]:
# try to matrix multiply X by reshaped Y


X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [63]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [64]:
# try changing the shape of X instead of Y

tf.matmul(tf.reshape(X, shape=(2,3)), Y )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [65]:
# can do the same with transpose

X, tf.transpose(X), tf.reshape (X, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [66]:
# try matrix mul with transpose rather than reshape

tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [67]:
# perform the dot product on X and Y 


tf.tensordot(tf.transpose(X), Y, axes =1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [68]:
# perform matrix mul b/w X and Y


tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [69]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [70]:
# check the values of Y, reshape Y and transpose Y

print('Normal Y: ')

print(Y, '\n')   # \n is for newline

print('Y reshaped to (2,3): ')
print(tf.reshape(Y, (2,3)),'\n')

print('Y transposed')
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [71]:
tf.matmul(X, tf.transpose(Y))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

## changing the datatype of a tensor

In [75]:
# create a new tensor with default datatype (int32)

B = tf.constant([11.7, 8.5])

B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([11.7,  8.5], dtype=float32)>,
 tf.float32)

In [73]:

C = tf.constant([11, 8])

C.dtype

tf.int32

In [76]:
# change float32 to float16 (reduced precision)

D = tf.cast (B, dtype = tf.float16)
D , D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([11.7,  8.5], dtype=float16)>,
 tf.float16)

In [78]:
# chang from int32 to float32

E = tf.cast (C, dtype=tf.float32)

E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([11.,  8.], dtype=float32)>

In [80]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([11.,  8.], dtype=float16)>

## Aggregating tensors

In [81]:
# get the absolute values

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [82]:
# get the absolute values

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

### lets go through the following forms of aggregation:

#### get the min
#### get the max
#### get the mean of tensor
#### get the sum of a tensor


In [83]:
# creating a random tensor with values 0 and 100 of size 50


E = tf.constant(np.random.randint(0, 100, size =50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([35, 95, 35, 61, 31, 78, 61, 50, 58, 26, 21, 89,  1, 80, 50, 79, 30,
       90, 54, 20, 25, 81, 82, 85, 71, 55, 42, 85, 51, 86, 79, 23, 10, 89,
       15, 59, 57, 50, 63, 68, 38, 30, 64, 84, 63, 69, 27, 37, 31, 75])>

In [85]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [87]:
# find the minimum

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [88]:
# find the maximum

tf.reduce_max(E)



<tf.Tensor: shape=(), dtype=int32, numpy=95>

In [89]:
# find the mean

tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=54>

In [90]:
# find the sum

tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2738>

In [102]:
# import tensorflow_probability as tfp

#!pip install tensorflow-probability

ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.5; Detected an installation of version 2.3.0. Please upgrade TensorFlow to proceed.

In [103]:
# !pip install --upgrade tensorflow

Could not fetch URL https://pypi.org/simple/tensorflow/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/tensorflow/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)'))) - skipping
Could not fetch URL https://pypi.org/simple/numpy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/numpy/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)'))) - skipping


ERROR: Could not find a version that satisfies the requirement numpy<1.19.0,>=1.16.0 (from tensorflow)
ERROR: No matching distribution found for numpy<1.19.0,>=1.16.0


In [98]:
# find the variance

tfp.stats.variance(E)

NameError: name 'tfp' is not defined

In [94]:
tfp.math.reduce_std(E)

TypeError: Input must be either real or complex

In [105]:
# find the std dev

tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=24.62727>

In [106]:
# find the variance

tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=606.50244>

## find the postional minimum and maximum

In [108]:
# create a new tensor fpr finding positional max and min

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [111]:
# find the positional max


tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [112]:
# indec on our largest value postion

F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [113]:
# find the max value of F

tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [115]:
# check for equality

F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [116]:
# find the positional min


tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [117]:
# indec on our min value postion

F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [118]:
# find the min value of F

tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [119]:
# check for equality

F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

## sqeezing a tensor (romoving all single dimensions)


In [121]:
# create a tensor to get started

tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [122]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [123]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One-hot encoding

In [124]:
# create a list of indices


some_list = [0,1,2,3]  # could be red, green, blue and purple



# one hot encode our list of indices

tf.one_hot(some_list, depth =4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [125]:
# specify the custon values for one hot encoding


tf.one_hot(some_list, depth = 4, on_value='I love DL, ML', off_value='i like to play')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love DL, ML', b'i like to play', b'i like to play',
        b'i like to play'],
       [b'i like to play', b'I love DL, ML', b'i like to play',
        b'i like to play'],
       [b'i like to play', b'i like to play', b'I love DL, ML',
        b'i like to play'],
       [b'i like to play', b'i like to play', b'i like to play',
        b'I love DL, ML']], dtype=object)>

In [126]:
# specify the custon values for one hot encoding


tf.one_hot(some_list, depth = 4, on_value='Arun', off_value='Nirmala')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Arun', b'Nirmala', b'Nirmala', b'Nirmala'],
       [b'Nirmala', b'Arun', b'Nirmala', b'Nirmala'],
       [b'Nirmala', b'Nirmala', b'Arun', b'Nirmala'],
       [b'Nirmala', b'Nirmala', b'Nirmala', b'Arun']], dtype=object)>

### Squaring, log, square root

In [127]:
# create a new tensor

H = tf.range(1, 10)

H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [128]:
# square it

tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [131]:
# square root

tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [132]:
# find the log

tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## tensors and Numpy


#### tf interacts beautifully with numpy

In [133]:
# create a tensor directly from a Numpy array

J = tf.constant(np.array([3., 7., 10.]))

J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [134]:
# convert our tensor back to a numpy array

np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [136]:
# convert tensor J to a numpy array

J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [137]:
J = tf.constant([3.])

J.numpy()[0]

3.0

In [138]:
# the default types of each are slightly different

numpy_J = tf.constant(np.array([3., 7., 10.]))

tensor_J = tf.constant([3., 7., 10.])

# check the dataype of each
numpy_J.dtype , tensor_J.dtype


(tf.float64, tf.float32)

In [139]:
# finding access to GPU/CPU

# if u r using google colab, then go to Runtime and change it to GPU. once changed , run the below items


tf.config.list_physical_devices()

#    !nvidia-smi  



[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]